[tool.poetry]
name = "ankix"
version = "0.1.0"
description = ""
authors = ["patarapolw <patarapolw@gmail.com>"]

[tool.poetry.dependencies]
python = "*"
peewee = "^3.7"
tqdm = "^4.27"
mistune = "^0.8.4"

[tool.poetry.dev-dependencies]
jupyter = "^1.0"
notebook = "^5.7"
htmlviewer = "^0.1.7"
